name: Docker Image CI

on:
  push:
    branches: [ master ]
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Publish the Docker image
      run: |
        docker build . --file Dockerfile --tag minibox:$(date +%s)
        docker-compose build
        docker-compose up
        docker login --username ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_PASS }}
        docker push foundeo/minibox:latest
        
