name: Docker Image CI

on:
  push:
    branches: [ master ]
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Publish the Docker image
      run: |
        docker build . --file Dockerfile --tag minibox
        docker-compose build
        docker-compose up
        echo "${{ secrets.DOCKER_PASS }}" | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
        docker tag minibox foundeo/minibox:latest
        docker push foundeo/minibox:latest
        
